In [1]:
import pandas as pd    

In [2]:
csv=pd.read_csv("snli_1.0_train.txt",sep="\t")
val_csv=pd.read_csv("snli_1.0_dev.txt",sep="\t")
test_csv=pd.read_csv("snli_1.0_test.txt",sep="\t")

In [3]:
from math import isnan

In [4]:
csv

gold_label                             sentence1_binary_parse  \
0             neutral  ( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...   
1       contradiction  ( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...   
2          entailment  ( ( ( A person ) ( on ( a horse ) ) ) ( ( jump...   
3             neutral  ( Children ( ( ( smiling and ) waving ) ( at c...   
4          entailment  ( Children ( ( ( smiling and ) waving ) ( at c...   
...               ...                                                ...   
550147  contradiction  ( ( ( ( Four dirty ) and ) ( barefooted childr...   
550148        neutral  ( ( ( ( Four dirty ) and ) ( barefooted childr...   
550149        neutral  ( ( A man ) ( ( is ( surfing ( in ( ( a bodysu...   
550150  contradiction  ( ( A man ) ( ( is ( surfing ( in ( ( a bodysu...   
550151     entailment  ( ( A man ) ( ( is ( surfing ( in ( ( a bodysu...   

                                   sentence2_binary_parse  \
0       ( ( A person ) ( ( is ( ( training ( his horse...   
1       ( ( A person ) ( ( ( ( is ( at ( a diner ) ) )...   
2       ( ( A person ) ( ( ( ( is outdoors ) , ) ( on ...   
3       ( They ( are ( smiling ( at ( their parents ) ...   
4                  ( There ( ( are children ) present ) )   
...                                                   ...   
550147  ( ( four kids ) ( ( won awards ) ( ( ( for ` )...   
550148  ( ( ( ( ( ( four ( homeless children ) ) ( had...   
550149  ( ( ( A man ) ( in ( a bodysuit ) ) ) ( ( is (...   
550150  ( ( ( A man ) ( in ( a ( business suit ) ) ) )...   
550151  ( ( On ( the ( beautiful ( blue water ) ) ) ) ...   

                                          sentence1_parse  \
0       (ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...   
1       (ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...   
2       (ROOT (S (NP (NP (DT A) (NN person)) (PP (IN o...   
3       (ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...   
4       (ROOT (NP (S (NP (NNP Children)) (VP (VBG smil...   
...                                                   ...   
550147  (ROOT (NP (NP (CD Four) (NNS dirty)) (CC and) ...   
550148  (ROOT (NP (NP (CD Four) (NNS dirty)) (CC and) ...   
550149  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   
550150  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   
550151  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   

                                          sentence2_parse  \
0       (ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...   
1       (ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...   
2       (ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) ...   
3       (ROOT (S (NP (PRP They)) (VP (VBP are) (VP (VB...   
4       (ROOT (S (NP (EX There)) (VP (VBP are) (NP (NN...   
...                                                   ...   
550147  (ROOT (S (NP (CD four) (NNS kids)) (VP (VBD wo...   
550148  (ROOT (S (S (NP (CD four) (JJ homeless) (NNS c...   
550149  (ROOT (S (NP (NP (DT A) (NN man)) (PP (IN in) ...   
550150  (ROOT (S (NP (NP (DT A) (NN man)) (PP (IN in) ...   
550151  (ROOT (S (PP (IN On) (NP (DT the) (JJ beautifu...   

                                                sentence1  \
0       A person on a horse jumps over a broken down a...   
1       A person on a horse jumps over a broken down a...   
2       A person on a horse jumps over a broken down a...   
3                   Children smiling and waving at camera   
4                   Children smiling and waving at camera   
...                                                   ...   
550147                Four dirty and barefooted children.   
550148                Four dirty and barefooted children.   
550149  A man is surfing in a bodysuit in beautiful bl...   
550150  A man is surfing in a bodysuit in beautiful bl...   
550151  A man is surfing in a bodysuit in beautiful bl...   

                                                sentence2         captionID  \
0       A person is training his horse for a competition.  3416050480.jpg#4   
1       

In [6]:
len(csv)

550152

In [7]:
csv2=csv[(csv["label1"].isnull()==False) & (csv["label2"].isnull()==False) 
    & (csv["label3"].isnull()==False) & (csv["label4"].isnull()==False) & (csv["label5"].isnull()==False)]

val_csv2=val_csv[(val_csv["label1"].isnull()==False) & (val_csv["label2"].isnull()==False) 
    & (val_csv["label3"].isnull()==False) & (val_csv["label4"].isnull()==False) & (val_csv["label5"].isnull()==False)]

test_csv2=test_csv[(test_csv["label1"].isnull()==False) & (test_csv["label2"].isnull()==False) 
    & (test_csv["label3"].isnull()==False) & (test_csv["label4"].isnull()==False) & (test_csv["label5"].isnull()==False)]

In [8]:
len(csv2)

36776

In [9]:
len(csv[(csv["label1"].isnull()==False) & (csv["label2"].isnull()==True) 
    & (csv["label3"].isnull()==False) & (csv["label4"].isnull()==False) & (csv["label5"].isnull()==True)])

17

In [10]:
data_l1=csv[(csv["label1"].isnull()==False) & (csv["gold_label"]!="-")].loc[:,["gold_label","label1"]]


In [11]:
from sklearn import metrics

In [12]:
import numpy as np

In [13]:
actual=data_l1["gold_label"]
#list(map(int,val_data["labels"]))

predicted=data_l1["label1"]
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted,normalize='true')

p1=[confusion_matrix[0,0],confusion_matrix[1,1],confusion_matrix[2,2]]

print(p1)

[0.9976308362492972, 0.9944225149387186, 0.99407432535948]


In [14]:
print(confusion_matrix)

[[9.97630836e-01 4.80383433e-04 1.88878032e-03]
 [2.67152266e-04 9.94422515e-01 5.31033280e-03]
 [2.34181786e-03 3.58385678e-03 9.94074325e-01]]


In [15]:
data_l1["gold_label"].value_counts()

entailment       183416
contradiction    183187
neutral          182764
Name: gold_label, dtype: int64

In [16]:
data_l2=csv[(csv["label2"].isnull()==False) & (csv["gold_label"]!="-")].loc[:,["gold_label","label2"]]

actual=data_l2["gold_label"]
#list(map(int,val_data["labels"]))

predicted=data_l2["label2"]
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted,normalize='true')

print(confusion_matrix)

p2=[confusion_matrix[0,0],confusion_matrix[1,1],confusion_matrix[2,2]]

print("\n",p2)

[[0.92225715 0.01725063 0.06049222]
 [0.02026614 0.90402264 0.07571123]
 [0.0747214  0.07616452 0.84911409]]

 [0.9222571494288124, 0.9040226368920159, 0.8491140864266816]


In [17]:
data_l3=csv[(csv["label3"].isnull()==False) & (csv["gold_label"]!="-")].loc[:,["gold_label","label3"]]

actual=data_l3["gold_label"]
#list(map(int,val_data["labels"]))

predicted=data_l3["label3"]
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted,normalize='true')

print(confusion_matrix)

p3=[confusion_matrix[0,0],confusion_matrix[1,1],confusion_matrix[2,2]]

print("\n",p3)

[[0.91937462 0.02245555 0.05816983]
 [0.03024748 0.89657806 0.07317446]
 [0.08508934 0.08524958 0.82966108]]

 [0.9193746167995095, 0.8965780629391995, 0.8296610848489704]


In [18]:
data_l4=csv[(csv["label4"].isnull()==False) & (csv["gold_label"]!="-")].loc[:,["gold_label","label4"]]

actual=data_l4["gold_label"]
#list(map(int,val_data["labels"]))

predicted=data_l4["label4"]
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted,normalize='true')

print(confusion_matrix)

p4=[confusion_matrix[0,0],confusion_matrix[1,1],confusion_matrix[2,2]]

print("\n",p4)

[[0.91966271 0.02200077 0.05833653]
 [0.02973324 0.90285103 0.06741573]
 [0.08782051 0.09855769 0.81362179]]

 [0.9196627060176312, 0.9028510280516701, 0.8136217948717949]


In [19]:
data_l5=csv[(csv["label5"].isnull()==False) & (csv["gold_label"]!="-")].loc[:,["gold_label","label5"]]

actual=data_l5["gold_label"]
#list(map(int,val_data["labels"]))

predicted=data_l5["label5"]
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted,normalize='true')

print(confusion_matrix)

p5=[confusion_matrix[0,0],confusion_matrix[1,1],confusion_matrix[2,2]]

print("\n",p5)

[[0.91585892 0.01726806 0.06687301]
 [0.01357944 0.92283298 0.06358758]
 [0.05857034 0.08886826 0.8525614 ]]

 [0.9158589231897043, 0.9228329809725159, 0.8525613975862942]


In [20]:
len(data_l5)

36424

In [21]:
csv2

gold_label                             sentence1_binary_parse  \
11            neutral  ( ( An ( older man ) ) ( ( ( sits ( with ( ( h...   
16      contradiction  ( ( ( A ( few people ) ) ( in ( ( ( a ( restau...   
26            neutral  ( ( ( Two women ) ( who ( just ( had ( lunch (...   
29         entailment  ( ( ( ( ( Two women ) , ) ( holding ( food ( c...   
34            neutral  ( ( The school ) ( ( is ( ( having ( ( a ( spe...   
...               ...                                                ...   
550093  contradiction  ( ( ( A man ) ( in ( a ( blue shirt ) ) ) ) ( ...   
550095     entailment  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
550097  contradiction  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
550124        neutral  ( ( ( Two men ) ( standing ( outside ( wearing...   
550134  contradiction  ( ( ( A group ) ( of ( people ( in ( orange ( ...   

                                   sentence2_binary_parse  \
11      ( ( An ( elderly man ) ) ( ( sits ( in ( a ( s...   
16      ( ( The people ) ( ( are ( sitting ( at ( desk...   
26      ( ( The friends ) ( ( ( ( ( ( have just ) ( me...   
29         ( ( Two women ) ( ( hug ( each other ) ) . ) )   
34      ( ( A ( high school ) ) ( ( is ( hosting ( an ...   
...                                                   ...   
550093  ( ( ( The water ) ( in ( the fountain ) ) ) ( ...   
550095            ( ( A ( garage door ) ) ( is moving ) )   
550097          ( ( The ( garage door ) ) ( is broken ) )   
550124  ( ( Two men ) ( ( are ( at ( a ( baseball game...   
550134       ( ( The ( life vests ) ) ( ( are red ) . ) )   

                                          sentence1_parse  \
11      (ROOT (S (NP (DT An) (JJR older) (NN man)) (VP...   
16      (ROOT (S (NP (NP (DT A) (JJ few) (NNS people))...   
26      (ROOT (NP (NP (CD Two) (NNS women)) (SBAR (WHN...   
29      (ROOT (S (NP (NP (CD Two) (NNS women)) (, ,) (...   
34      (ROOT (S (NP (DT The) (NN school)) (VP (VBZ is...   
...                                                   ...   
550093  (ROOT (S (NP (NP (DT A) (NN man)) (PP (IN in) ...   
550095  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
550097  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
550124  (ROOT (NP (NP (CD Two) (NNS men)) (VP (VBG sta...   
550134  (ROOT (S (NP (NP (DT A) (NN group)) (PP (IN of...   

                                          sentence2_parse  \
11      (ROOT (S (NP (DT An) (JJ elderly) (NN man)) (V...   
16      (ROOT (S (NP (DT The) (NNS people)) (VP (VBP a...   
26      (ROOT (S (NP (DT The) (NNS friends)) (VP (VP (...   
29      (ROOT (S (NP (CD Two) (NNS women)) (VP (VB hug...   
34      (ROOT (S (NP (DT A) (JJ high) (NN school)) (VP...   
...                                                   ...   
550093  (ROOT (S (NP (NP (DT The) (NN water)) (PP (IN ...   
550095  (ROOT (S (NP (DT A) (NN garage) (NN door)) (VP...   
550097  (ROOT (S (NP (DT The) (NN garage) (NN door)) (...   
550124  (ROOT (S (NP (CD Two) (NNS men)) (VP (VBP are)...   
550134  (ROOT (S (NP (DT The) (NN life) (NNS vests)) (...   

                                                sentence1  \
11      An older man sits with his orange juice at a s...   
16      A few people in a restaurant setting, one of t...   
26      Two women who just had lunch hugging and sayin...   
29      Two women, holding food carryout containers, hug.   
34      The school is having a special event in order ...   
...                                                   ...   
550093  A man in a blue shirt locks a blue shutter nex...   
550095  A man raising or lowering a blue and red garag...   
550097  A man raising or lowering a blue and red garag...   
550124  Two men standing outside wearing jackets and c...   
550134  A group of people in orange life vests are boa...   

                                                sentence2         captionID  \
11                   An elderly man sits in a small shop.  4804607632.jpg#0   
16      

In [22]:
mapping={"entailment":0,"neutral":1,"contradiction":2}

csv2=csv2.replace(to_replace="entailment",value=0)
csv2=csv2.replace(to_replace="neutral",value=1)
csv2=csv2.replace(to_replace="contradiction",value=2)

val_csv2 =val_csv2.replace(to_replace="entailment",value=0)
val_csv2 =val_csv2.replace(to_replace="neutral",value=1)
val_csv2 =val_csv2.replace(to_replace="contradiction",value=2)

test_csv2=test_csv2.replace(to_replace="entailment",value=0)
test_csv2=test_csv2.replace(to_replace="neutral",value=1)
test_csv2=test_csv2.replace(to_replace="contradiction",value=2)


In [23]:
csv2.reset_index(inplace=True)
val_csv2.reset_index(inplace=True)
test_csv2.reset_index(inplace=True)

In [24]:
csv2

index gold_label                             sentence1_binary_parse  \
0          11          1  ( ( An ( older man ) ) ( ( ( sits ( with ( ( h...   
1          16          2  ( ( ( A ( few people ) ) ( in ( ( ( a ( restau...   
2          26          1  ( ( ( Two women ) ( who ( just ( had ( lunch (...   
3          29          0  ( ( ( ( ( Two women ) , ) ( holding ( food ( c...   
4          34          1  ( ( The school ) ( ( is ( ( having ( ( a ( spe...   
...       ...        ...                                                ...   
36771  550093          2  ( ( ( A man ) ( in ( a ( blue shirt ) ) ) ) ( ...   
36772  550095          0  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
36773  550097          2  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
36774  550124          1  ( ( ( Two men ) ( standing ( outside ( wearing...   
36775  550134          2  ( ( ( A group ) ( of ( people ( in ( orange ( ...   

                                  sentence2_binary_parse  \
0      ( ( An ( elderly man ) ) ( ( sits ( in ( a ( s...   
1      ( ( The people ) ( ( are ( sitting ( at ( desk...   
2      ( ( The friends ) ( ( ( ( ( ( have just ) ( me...   
3         ( ( Two women ) ( ( hug ( each other ) ) . ) )   
4      ( ( A ( high school ) ) ( ( is ( hosting ( an ...   
...                                                  ...   
36771  ( ( ( The water ) ( in ( the fountain ) ) ) ( ...   
36772            ( ( A ( garage door ) ) ( is moving ) )   
36773          ( ( The ( garage door ) ) ( is broken ) )   
36774  ( ( Two men ) ( ( are ( at ( a ( baseball game...   
36775       ( ( The ( life vests ) ) ( ( are red ) . ) )   

                                         sentence1_parse  \
0      (ROOT (S (NP (DT An) (JJR older) (NN man)) (VP...   
1      (ROOT (S (NP (NP (DT A) (JJ few) (NNS people))...   
2      (ROOT (NP (NP (CD Two) (NNS women)) (SBAR (WHN...   
3      (ROOT (S (NP (NP (CD Two) (NNS women)) (, ,) (...   
4      (ROOT (S (NP (DT The) (NN school)) (VP (VBZ is...   
...                                                  ...   
36771  (ROOT (S (NP (NP (DT A) (NN man)) (PP (IN in) ...   
36772  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
36773  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
36774  (ROOT (NP (NP (CD Two) (NNS men)) (VP (VBG sta...   
36775  (ROOT (S (NP (NP (DT A) (NN group)) (PP (IN of...   

                                         sentence2_parse  \
0      (ROOT (S (NP (DT An) (JJ elderly) (NN man)) (V...   
1      (ROOT (S (NP (DT The) (NNS people)) (VP (VBP a...   
2      (ROOT (S (NP (DT The) (NNS friends)) (VP (VP (...   
3      (ROOT (S (NP (CD Two) (NNS women)) (VP (VB hug...   
4      (ROOT (S (NP (DT A) (JJ high) (NN school)) (VP...   
...                                                  ...   
36771  (ROOT (S (NP (NP (DT The) (NN water)) (PP (IN ...   
36772  (ROOT (S (NP (DT A) (NN garage) (NN door)) (VP...   
36773  (ROOT (S (NP (DT The) (NN garage) (NN door)) (...   
36774  (ROOT (S (NP (CD Two) (NNS men)) (VP (VBP are)...   
36775  (ROOT (S (NP (DT The) (NN life) (NNS vests)) (...   

                                               sentence1  \
0      An older man sits with his orange juice at a s...   
1      A few people in a restaurant setting, one of t...   
2      Two women who just had lunch hugging and sayin...   
3      Two women, holding food carryout containers, hug.   
4      The school is having a special event in order ...   
...                                                  ...   
36771  A man in a blue shirt locks a blue shutter nex...   
36772  A man raising or lowering a blue and red garag...   
36773  A man raising or lowering a blue and red garag...   
36774  Two men standing outside wearing jackets and c...   
36775  A group of people in orange life vests are boa...   

                                               sentence2         captionID  \
0                   An elderly man sits in a small shop.  4804607632.jpg#0   
1             The p

In [25]:
import torch

In [26]:
csv_labels=csv2.loc[:,["label1","label2","label3","label4","label5"]]
l_probas=[p1,p2,p3,p4,p5]

probas_finale=[]
a=0
for i in range(len(csv_labels)):
    proba=[0.0,0.0,0.0]
    for j in range(5):
        index=csv_labels.iloc[i,j]
        proba[index]+=l_probas[j][index]
    probas_finale.append(proba/sum(proba))
    
    
csv2=csv2.replace(to_replace="-",value=9)
actual=list(csv2["gold_label"].astype({"gold_label":int}))
#list(map(int,val_data["labels"]))

predicted=torch.argmax(torch.Tensor(probas_finale),dim=-1).tolist()
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted)

print(confusion_matrix)

csv2.insert(0,"probas_label",probas_finale)

csv2

[[12263     0     0     0]
 [    0 11818     0     0]
 [    0     0 12222     0]
 [  194   241    38     0]]


probas_label   index  gold_label  \
0       [0.41255094187474917, 0.587449058125251, 0.0]      11           1   
1                                     [0.0, 0.0, 1.0]      16           2   
2                                     [0.0, 1.0, 0.0]      26           1   
3       [0.8151222258839104, 0.0, 0.1848777741160897]      29           0   
4      [0.19850712866030096, 0.8014928713396992, 0.0]      34           1   
...                                               ...     ...         ...   
36771                                 [0.0, 0.0, 1.0]  550093           2   
36772   [0.8058599840189417, 0.1941400159810583, 0.0]  550095           0   
36773  [0.0, 0.40583981573715283, 0.5941601842628471]  550097           2   
36774                                 [0.0, 1.0, 0.0]  550124           1   
36775                                 [0.0, 0.0, 1.0]  550134           2   

                                  sentence1_binary_parse  \
0      ( ( An ( older man ) ) ( ( ( sits ( with ( ( h...   
1      ( ( ( A ( few people ) ) ( in ( ( ( a ( restau...   
2      ( ( ( Two women ) ( who ( just ( had ( lunch (...   
3      ( ( ( ( ( Two women ) , ) ( holding ( food ( c...   
4      ( ( The school ) ( ( is ( ( having ( ( a ( spe...   
...                                                  ...   
36771  ( ( ( A man ) ( in ( a ( blue shirt ) ) ) ) ( ...   
36772  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
36773  ( ( A man ) ( ( ( ( ( raising or ) lowering ) ...   
36774  ( ( ( Two men ) ( standing ( outside ( wearing...   
36775  ( ( ( A group ) ( of ( people ( in ( orange ( ...   

                                  sentence2_binary_parse  \
0      ( ( An ( elderly man ) ) ( ( sits ( in ( a ( s...   
1      ( ( The people ) ( ( are ( sitting ( at ( desk...   
2      ( ( The friends ) ( ( ( ( ( ( have just ) ( me...   
3         ( ( Two women ) ( ( hug ( each other ) ) . ) )   
4      ( ( A ( high school ) ) ( ( is ( hosting ( an ...   
...                                                  ...   
36771  ( ( ( The water ) ( in ( the fountain ) ) ) ( ...   
36772            ( ( A ( garage door ) ) ( is moving ) )   
36773          ( ( The ( garage door ) ) ( is broken ) )   
36774  ( ( Two men ) ( ( are ( at ( a ( baseball game...   
36775       ( ( The ( life vests ) ) ( ( are red ) . ) )   

                                         sentence1_parse  \
0      (ROOT (S (NP (DT An) (JJR older) (NN man)) (VP...   
1      (ROOT (S (NP (NP (DT A) (JJ few) (NNS people))...   
2      (ROOT (NP (NP (CD Two) (NNS women)) (SBAR (WHN...   
3      (ROOT (S (NP (NP (CD Two) (NNS women)) (, ,) (...   
4      (ROOT (S (NP (DT The) (NN school)) (VP (VBZ is...   
...                                                  ...   
36771  (ROOT (S (NP (NP (DT A) (NN man)) (PP (IN in) ...   
36772  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
36773  (ROOT (S (NP (DT A) (NN man)) (VP (VBG raising...   
36774  (ROOT (NP (NP (CD Two) (NNS men)) (VP (VBG sta...   
36775  (ROOT (S (NP (NP (DT A) (NN group)) (PP (IN of...   

                                         sentence2_parse  \
0      (ROOT (S (NP (DT An) (JJ elderly) (NN man)) (V...   
1      (ROOT (S (NP (DT The) (NNS people)) (VP (VBP a...   
2      (ROOT (S (NP (DT The) (NNS friends)) (VP (VP (...   
3      (ROOT (S (NP (CD Two) (NNS women)) (VP (VB hug...   
4      (ROOT (S (NP (DT A) (JJ high) (NN school)) (VP...   
...                                                  ...   
36771  (ROOT (S (NP (NP (DT The) (NN water)) (PP (IN ...   
36772  (ROOT (S (NP (DT A) (NN garage) (NN door)) (VP...   
36773  (ROOT (S (NP (DT The) (NN garage) (NN door)) (...   
36774  (ROOT (S (NP (CD Two) (NNS men)) (VP (VBP are)...   
36775  (ROOT (S (NP (DT The) (NN life) (NNS vests)) (...   

                                               sentence1  \
0      An older man sits with his orange juice at a s...   
1      A few people in a restaurant setting, one of t...   
2      Two women who just had lunch hugging and sayi

In [27]:
val_csv_labels=val_csv2.loc[:,["label1","label2","label3","label4","label5"]]

probas_finale=[]

for i in range(len(val_csv_labels)):
    proba=[0.0,0.0,0.0]
    for j in range(5):
        index=val_csv_labels.iloc[i,j]
        proba[index]+=l_probas[j][index]
    probas_finale.append(proba/sum(proba))
    
    
val_csv2=val_csv2.replace(to_replace="-",value=9)
actual=list(val_csv2["gold_label"].astype({"gold_label":int}))
#list(map(int,val_data["labels"]))

predicted=torch.argmax(torch.Tensor(probas_finale),dim=-1).tolist()
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted)

print(confusion_matrix)

val_csv2.insert(0,"probas_label",probas_finale)

val_csv2

[[3325    0    0    0]
 [   0 3231    0    0]
 [   0    0 3275    0]
 [  56   83   16    0]]


probas_label  index  gold_label  \
0         [0.1988076595586334, 0.8011923404413666, 0.0]      0           1   
1                                       [1.0, 0.0, 0.0]      1           0   
2                                       [0.0, 0.0, 1.0]      2           2   
3                                       [1.0, 0.0, 0.0]      3           0   
4         [0.3963943101846237, 0.6036056898153764, 0.0]      4           1   
...                                                 ...    ...         ...   
9981                                    [1.0, 0.0, 0.0]   9994           0   
9982                                    [0.0, 0.0, 1.0]   9996           2   
9983                                    [1.0, 0.0, 0.0]   9997           0   
9984  [0.20435007300798905, 0.2051187661591033, 0.59...   9998           2   
9985  [0.20089803851338098, 0.6128447223879419, 0.18...   9999           1   

                                 sentence1_binary_parse  \
0     ( ( Two women ) ( ( are ( embracing ( while ( ...   
1     ( ( Two women ) ( ( are ( embracing ( while ( ...   
2     ( ( Two women ) ( ( are ( embracing ( while ( ...   
3     ( ( ( Two ( young children ) ) ( in ( ( ( ( ( ...   
4     ( ( ( Two ( young children ) ) ( in ( ( ( ( ( ...   
...                                                 ...   
9981  ( ( ( A ( small girl ) ) ( wearing ( a ( pink ...   
9982  ( ( ( A ( small girl ) ) ( wearing ( a ( pink ...   
9983  ( ( ( A ( young girl ) ) ( with ( ( ( ( ( ( bl...   
9984  ( ( ( A ( young girl ) ) ( with ( ( ( ( ( ( bl...   
9985  ( ( ( A ( young girl ) ) ( with ( ( ( ( ( ( bl...   

                                 sentence2_binary_parse  \
0     ( ( The sisters ) ( ( are ( ( hugging goodbye ...   
1     ( ( Two woman ) ( ( are ( holding packages ) )...   
2     ( ( The men ) ( ( are ( fighting ( outside ( a...   
3     ( ( ( Two kids ) ( in ( numbered jerseys ) ) )...   
4     ( ( ( Two kids ) ( at ( a ballgame ) ) ) ( ( w...   
...                                                 ...   
9981           ( ( The carousel ) ( ( is moving ) . ) )   
9982  ( ( The girl ) ( ( is ( moving ( at ( ( the sp...   
9983         ( People ( in ( a ( water fountain ) ) ) )   
9984   ( ( ( A ( young girl ) ) knits ) ( a sweater ) )   
9985  ( ( A ( young mother ) ) ( tries ( to ( ( ( gr...   

                                        sentence1_parse  \
0     (ROOT (S (NP (CD Two) (NNS women)) (VP (VBP ar...   
1     (ROOT (S (NP (CD Two) (NNS women)) (VP (VBP ar...   
2     (ROOT (S (NP (CD Two) (NNS women)) (VP (VBP ar...   
3     (ROOT (S (NP (NP (CD Two) (JJ young) (NNS chil...   
4     (ROOT (S (NP (NP (CD Two) (JJ young) (NNS chil...   
...                                                 ...   
9981  (ROOT (S (NP (NP (DT A) (JJ small) (NN girl)) ...   
9982  (ROOT (S (NP (NP (DT A) (JJ small) (NN girl)) ...   
9983  (ROOT (NP (NP (DT A) (JJ young) (NN girl)) (PP...   
9984  (ROOT (NP (NP (DT A) (JJ young) (NN girl)) (PP...   
9985  (ROOT (NP (NP (DT A) (JJ young) (NN girl)) (PP...   

                                        sentence2_parse  \
0     (ROOT (S (NP (DT The) (NNS sisters)) (VP (VBP ...   
1     (ROOT (S (NP (CD Two) (NN woman)) (VP (VBP are...   
2     (ROOT (S (NP (DT The) (NNS men)) (VP (VBP are)...   
3     (ROOT (S (NP (NP (CD Two) (NNS kids)) (PP (IN ...   
4     (ROOT (S (NP (NP (CD Two) (NNS kids)) (PP (IN ...   
...                                                 ...   
9981  (ROOT (S (NP (DT The) (NN carousel)) (VP (VBZ ...   
9982  (ROOT (S (NP (DT The) (NN girl)) (VP (VBZ is) ...   
9983  (ROOT (NP (NP (NNS People)) (PP (IN in) (NP (D...   
9984  (ROOT (NP (NP (DT A) (JJ young) (NN girl)) (NP...   
9985  (ROOT (S (NP (DT A) (JJ young) (NN mother)) (V...   

                                              sentence1  \
0     Two women are embracing while holding to go pa...   
1     Two women are embracing while holding to go pa...   
2     Two women are embracing while holding to go pa...   
3     Two young children in blue j

In [28]:
test_csv_labels=test_csv2.loc[:,["label1","label2","label3","label4","label5"]]
l_probas=[p1,p2,p3,p4,p5]

probas_finale=[]

for i in range(len(test_csv_labels)):
    proba=[0.0,0.0,0.0]
    for j in range(5):
        index=test_csv_labels.iloc[i,j]
        proba[index]+=l_probas[j][index]
    probas_finale.append(proba/sum(proba))
    
    
test_csv2=test_csv2.replace(to_replace="-",value=9)
actual=list(test_csv2["gold_label"].astype({"gold_label":int}))
#list(map(int,val_data["labels"]))

predicted=torch.argmax(torch.Tensor(probas_finale),dim=-1).tolist()
#list(map(int,val_preds))

confusion_matrix = metrics.confusion_matrix(actual, predicted)

print(confusion_matrix)

test_csv2.insert(0,"probas_label",probas_finale)

test_csv2

[[3364    0    0    0]
 [   0 3215    0    0]
 [   0    0 3236    0]
 [  65   83   27    0]]


probas_label  index  gold_label  \
0        [0.0, 0.6268461175468555, 0.37315388245314457]      0           1   
1          [0.806170814095755, 0.1938291859042451, 0.0]      1           0   
2                                       [0.0, 0.0, 1.0]      2           2   
3                                       [0.0, 1.0, 0.0]      3           1   
4     [0.6183630259803904, 0.20096341166140166, 0.18...      4           0   
...                                                 ...    ...         ...   
9985                                    [0.0, 0.0, 1.0]   9995           2   
9986     [0.8219156258540289, 0.0, 0.17808437414597114]   9996           0   
9987                                    [0.0, 0.0, 1.0]   9997           2   
9988       [0.806170814095755, 0.1938291859042451, 0.0]   9998           0   
9989                                    [0.0, 1.0, 0.0]   9999           1   

                                 sentence1_binary_parse  \
0     ( ( This ( church choir ) ) ( ( ( sings ( to (...   
1     ( ( This ( church choir ) ) ( ( ( sings ( to (...   
2     ( ( This ( church choir ) ) ( ( ( sings ( to (...   
3     ( ( ( A woman ) ( with ( ( ( ( ( a ( green hea...   
4     ( ( ( A woman ) ( with ( ( ( ( ( a ( green hea...   
...                                                 ...   
9985  ( ( Two women ) ( ( are ( ( observing somethin...   
9986  ( ( Two women ) ( ( are ( ( observing somethin...   
9987  ( ( ( ( ( A man ) ( in ( a ( black ( leather j...   
9988  ( ( ( ( ( A man ) ( in ( a ( black ( leather j...   
9989  ( ( ( ( ( A man ) ( in ( a ( black ( leather j...   

                                 sentence2_binary_parse  \
0     ( ( The church ) ( ( has ( cracks ( in ( the c...   
1     ( ( The church ) ( ( is ( filled ( with song )...   
2     ( ( ( A choir ) ( singing ( at ( a ( baseball ...   
3                  ( ( The woman ) ( ( is young ) . ) )   
4         ( ( The woman ) ( ( is ( very happy ) ) . ) )   
...                                                 ...   
9985  ( ( ( Two women ) ( are ( standing ( with ( th...   
9986  ( ( Two girls ) ( ( are ( looking ( at somethi...   
9987   ( ( A man ) ( ( is ( flying ( a kite ) ) ) . ) )   
9988  ( ( A man ) ( ( is ( speaking ( in ( a classro...   
9989  ( ( A man ) ( ( is ( ( teaching science ) ( in...   

                                        sentence1_parse  \
0     (ROOT (S (NP (DT This) (NN church) (NN choir))...   
1     (ROOT (S (NP (DT This) (NN church) (NN choir))...   
2     (ROOT (S (NP (DT This) (NN church) (NN choir))...   
3     (ROOT (NP (NP (DT A) (NN woman)) (PP (IN with)...   
4     (ROOT (NP (NP (DT A) (NN woman)) (PP (IN with)...   
...                                                 ...   
9985  (ROOT (S (NP (CD Two) (NNS women)) (VP (VBP ar...   
9986  (ROOT (S (NP (CD Two) (NNS women)) (VP (VBP ar...   
9987  (ROOT (S (NP (NP (NP (DT A) (NN man)) (PP (IN ...   
9988  (ROOT (S (NP (NP (NP (DT A) (NN man)) (PP (IN ...   
9989  (ROOT (S (NP (NP (NP (DT A) (NN man)) (PP (IN ...   

                                        sentence2_parse  \
0     (ROOT (S (NP (DT The) (NN church)) (VP (VBZ ha...   
1     (ROOT (S (NP (DT The) (NN church)) (VP (VBZ is...   
2     (ROOT (NP (NP (DT A) (NN choir)) (VP (VBG sing...   
3     (ROOT (S (NP (DT The) (NN woman)) (VP (VBZ is)...   
4     (ROOT (S (NP (DT The) (NN woman)) (VP (VBZ is)...   
...                                                 ...   
9985  (ROOT (S (NP (NP (CD Two) (NNS women)) (SBAR (...   
9986  (ROOT (S (NP (CD Two) (NNS girls)) (VP (VBP ar...   
9987  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   
9988  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   
9989  (ROOT (S (NP (DT A) (NN man)) (VP (VBZ is) (VP...   

                                              sentence1  \
0     This church choir sings to the masses as they ...   
1     This church choir sings to the masses as they ...   
2     This church choir sings to the masses as they ...   
3     A woman with a green headsca

In [29]:
probas_finale

[array([0.        , 0.62684612, 0.37315388]),
 array([0.80617081, 0.19382919, 0.        ]),
 array([0., 0., 1.]),
 array([0., 1., 0.]),
 array([0.61836303, 0.20096341, 0.18067356]),
 array([0.        , 0.20349258, 0.79650742]),
 array([1., 0., 0.]),
 array([0.19799157, 0.80200843, 0.        ]),
 array([0.      , 0.205743, 0.794257]),
 array([0.        , 0.63192733, 0.36807267]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0.59020305, 0.40979695, 0.        ]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0., 0., 1.]),
 array([0.        , 0.82045112, 0.17954888]),
 array([1., 0., 0.]),
 array([0., 0., 1.]),
 array([0.20089804, 0.61284472, 0.18625724]),
 array([0.20803958, 0.        , 0.79196042]),
 array([1., 0., 0.]),
 array([0.        , 0.62856917, 0.37143083]),
 array([0.19850713, 0.80149287, 0.        ]),
 array([0., 0., 1.]),
 array([0.80288752, 0.19711248, 0.        ]),
 array([0.80288752, 0.19711248, 0.        ]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 array([

In [30]:
csv_labels.iloc[i,j].dtype

dtype('int64')

In [31]:
csv_labels.iloc[0,1]

1

In [32]:
i=0
for elt in csv2["probas_label"]:
    if (elt[0]+elt[1]+elt[2]!=1):
        print("SUM :",sum(elt))
        i+=1

Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
E

Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 0.9999999999999999
Error : 1.0000000000000002
Error : 1.0000000000000002
Error : 0.9999999999999999
E

In [33]:
i/len(csv2)

0.05150097889928214

In [ ]:
csv2.to_csv("train_snli_probas.csv")
val_csv2.to_csv("validation_snli_probas.csv")
test_csv2.to_csv("test_snli_probas.csv")