<a href="https://colab.research.google.com/github/TheoLpr/NLI_study/blob/main/Multi_task_Training_general_probas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Library setup

In [ ]:
!pip install -q --upgrade transformers
!pip install nlp==0.2.0
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 67.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 27.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 109.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 56.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 857.1/857.1 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 15.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.2/486.2 kB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 16.7 MB/s eta 0:00:00


In [ ]:
!pip uninstall accelerate

!pip install accelerate==0.20.3

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import transformers
import nlp
import logging
logging.basicConfig(level=logging.INFO)

##DATA LOADING


In [ ]:
import datasets
data=datasets.load_dataset("snli")


Downloading:   0%|          | 0.00/1.93k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/65.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.26M [00:00<?, ?B/s]

Dataset snli downloaded and prepared to /root/.cache/huggingface/datasets/snli/plain_text/1.0.0/1f60b67533b65ae0275561ff7828aad5ee4282d0e6f844fd148d05d3c6ea251b. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
train_data = data["train"].filter(lambda _ex: _ex["label"] != -1).select(range(50000))
val_data = data["validation"].filter(lambda _ex: _ex["label"] != -1)
test_data = data["test"].filter(lambda _ex: _ex["label"] != -1)

Filter:   0%|          | 0/550152 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10000 [00:00<?, ? examples/s]

In [ ]:
from datasets import DatasetDict

In [ ]:
snli=DatasetDict({"train":train_data, "validation":val_data, "test":test_data})

In [ ]:
snli

DatasetDict({
    train: Dataset({
        features: ['premise', 'hypothesis', 'label'],
        num_rows: 50000
    })
    validation: Dataset({
        features: ['premise', 'hypothesis', 'label'],
        num_rows: 9842
    })
    test: Dataset({
        features: ['premise', 'hypothesis', 'label'],
        num_rows: 9824
    })
})

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from datasets import load_from_disk

train_data2=load_from_disk("/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/train_data_inv_probas").remove_columns(["input_ids","attention_mask"])
test_data2=load_from_disk("/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/test_data_inv_probas").remove_columns(["input_ids","attention_mask"]).rename_column("hypothesis","temp").rename_column("premise","hypothesis").rename_column("temp","premise")
val_data2=load_from_disk("/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/val_data_inv_probas").remove_columns(["input_ids","attention_mask"])

In [ ]:
train_data2

Dataset({
    features: ['hypothesis', 'premise', 'label'],
    num_rows: 50000
})

In [ ]:
#Preprocessing the "inverse data"

def probas_truncation(dataset):

    if (dataset["label_2"]==0):
      dataset["label"][0]+=dataset["label"][2]/2.0
      dataset["label"][1]+=dataset["label"][2]/2.0
      dataset["label"][2]=0.0

    elif(dataset["label_2"]==2) :
      dataset["label"][2]+=dataset["label"][0]/2.0
      dataset["label"][1]+=dataset["label"][0]/2.0
      dataset["label"][0]=0.0

    return dataset

train_data2=train_data2.add_column('label_2',snli["train"]["label"])
test_data2=test_data2.add_column('label_2',snli["test"]["label"])
val_data2=val_data2.add_column('label_2',snli["validation"]["label"])

train_data2=train_data2.map(probas_truncation)
val_data2=val_data2.map(probas_truncation)
test_data2=test_data2.map(probas_truncation)


In [ ]:
train_data2["label_2"]

tensor([1, 2, 0,  ..., 0, 2, 0])

In [ ]:
train_data2["label"]

tensor([[0.0075, 0.0729, 0.9196],
        [0.0000, 0.0400, 0.9600],
        [0.4430, 0.5570, 0.0000],
        ...,
        [0.0767, 0.9233, 0.0000],
        [0.0000, 0.0694, 0.9306],
        [0.3106, 0.6894, 0.0000]])

In [ ]:
snli_inv=DatasetDict({"train":train_data2, "validation":val_data2, "test":test_data2})

In [ ]:
dataset_dict = {
    "snli": snli,
    "snli_inv": snli_inv
}

In [ ]:
snli_inv

DatasetDict({
    train: Dataset({
        features: ['hypothesis', 'premise', 'label', 'label_2'],
        num_rows: 50000
    })
    validation: Dataset({
        features: ['hypothesis', 'premise', 'label', 'label_2'],
        num_rows: 9842
    })
    test: Dataset({
        features: ['hypothesis', 'premise', 'label', 'label_2'],
        num_rows: 9824
    })
})

In [ ]:
for task_name, dataset in dataset_dict.items():
    print(task_name)
    print(dataset_dict[task_name]["train"][0])
    print()

snli
{'premise': 'A person on a horse jumps over a broken down airplane.', 'hypothesis': 'A person is training his horse for a competition.', 'label': 1}

snli_inv
{'hypothesis': 'A person on a horse jumps over a broken down airplane.', 'premise': 'A person is training his horse for a competition.', 'label': tensor([0.0075, 0.0729, 0.9196]), 'label_2': tensor(1)}



## Creating a Multi-task Model


In [ ]:
class MultitaskModel(transformers.PreTrainedModel):
    def __init__(self, encoder, taskmodels_dict):
        """
        Setting MultitaskModel up as a PretrainedModel allows us
        to take better advantage of Trainer features
        """
        super().__init__(transformers.PretrainedConfig())

        self.encoder = encoder
        self.taskmodels_dict = nn.ModuleDict(taskmodels_dict)

    @classmethod
    def create(cls, model_name, model_type_dict, model_config_dict):
        """
        This creates a MultitaskModel using the model class and config objects
        from single-task models.

        We do this by creating each single-task model, and having them share
        the same encoder transformer.
        """
        shared_encoder = None
        taskmodels_dict = {}
        for task_name, model_type in model_type_dict.items():
            model = model_type.from_pretrained(
                model_name,
                config=model_config_dict[task_name],
            )
            if shared_encoder is None:
                shared_encoder = getattr(model, cls.get_encoder_attr_name(model))
            else:
                setattr(model, cls.get_encoder_attr_name(model), shared_encoder)
            taskmodels_dict[task_name] = model
        return cls(encoder=shared_encoder, taskmodels_dict=taskmodels_dict)

    @classmethod
    def get_encoder_attr_name(cls, model):
        """
        The encoder transformer is named differently in each model "architecture".
        This method lets us get the name of the encoder attribute
        """
        model_class_name = model.__class__.__name__
        if model_class_name.startswith("Bert"):
            return "bert"
        elif model_class_name.startswith("Roberta"):
            return "roberta"
        elif model_class_name.startswith("Albert"):
            return "albert"
        else:
            raise KeyError(f"Add support for new model {model_class_name}")

    def forward(self, task_name, **kwargs):
        return self.taskmodels_dict[task_name](**kwargs)

In [ ]:
model_name = "roberta-base"
multitask_model = MultitaskModel.create(
    model_name=model_name,
    model_type_dict={
        "snli": transformers.AutoModelForSequenceClassification,
        "snli_inv": transformers.AutoModelForSequenceClassification,
    },
    model_config_dict={
        "snli": transformers.AutoConfig.from_pretrained(model_name, num_labels=3),
        "snli_inv": transformers.AutoConfig.from_pretrained(model_name, num_labels=3),
    },
)

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should pr

To confirm that all three task-models use the same encoder, we can check the data pointers of the respective encoders. In this case, we'll check that the word embeddings in each model all point to the same memory location.

In [ ]:
if model_name.startswith("roberta-"):
    print(multitask_model.encoder.embeddings.word_embeddings.weight.data_ptr())
    print(multitask_model.taskmodels_dict["snli"].roberta.embeddings.word_embeddings.weight.data_ptr())
    print(multitask_model.taskmodels_dict["snli_inv"].roberta.embeddings.word_embeddings.weight.data_ptr())
else:
    print("Exercise for the reader: add a check for other model architectures =)")

139664478208064
139664478208064
139664478208064


## Processing our task data

We have created a dictionary of NLP datasets above, but we need to do a little more work to convert the respective task data into model inputs.

We'll start by first getting the tokenizer corresponding to our model.

In [ ]:
tokenizer = transformers.AutoTokenizer.from_pretrained(model_name)

Next, we'll write some short functions to convert from raw text to tokenized text inputs.

* Both STS-B and RTE and two-sentence input tasks, so we will concatenate them with the corresponding special tokens. (The tokenizer's `batch_encode_plus` method handles this for us.) So, the input might look like:

```
['<s>', 'This', 'is', 'my', 'premise', '.', '</s>', '</s>', 'This', 'is', 'my', 'hypothesis', '.', '</s>']
```

* CommonsenseQA, is a multiple choice task. A single example consists of a question, a five possible answer choices. We will feed the model inputs concatenated like `QUESTION + CHOICE_1`, `QUESTION + CHOICE_2` and so on.

In [ ]:
max_length = 128

def convert_to_snli_features(example_batch):
    inputs = list(zip(example_batch['premise'], example_batch['hypothesis']))
    features = tokenizer.batch_encode_plus(
        inputs, max_length=max_length, pad_to_max_length=True
    )
    features["labels"] = example_batch["label"]
    return features

def convert_to_snli_inv_features(example_batch):
    inputs = list(zip(example_batch['hypothesis'], example_batch['premise']))
    features = tokenizer.batch_encode_plus(
        inputs, max_length=max_length, pad_to_max_length=True
    )
    features["labels"] = example_batch["label"]
    return features


convert_func_dict = {
    "snli": convert_to_snli_features,
    "snli_inv": convert_to_snli_inv_features,
}

Now that we have defined the above functions, we can use `dataset.map` method available in the NLP library to apply the functions over our entire datasets. The NLP library that handles the mapping efficiently and caches the features.

In [ ]:
columns_dict = {
    "snli": ['input_ids', 'attention_mask', 'labels'],
    "snli_inv": ['input_ids', 'attention_mask', 'labels'],
}

features_dict = {}
for task_name, dataset in dataset_dict.items():
    features_dict[task_name] = {}
    for phase, phase_dataset in dataset.items():
        features_dict[task_name][phase] = phase_dataset.map(
            convert_func_dict[task_name],
            batched=True,
            load_from_cache_file=False,
        )
        print(task_name, phase, len(phase_dataset), len(features_dict[task_name][phase]))
        features_dict[task_name][phase].set_format(
            type="torch",
            columns=columns_dict[task_name],
        )
        print(task_name, phase, len(phase_dataset), len(features_dict[task_name][phase]))

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2377: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


snli train 50000 50000
snli train 50000 50000


Map:   0%|          | 0/9842 [00:00<?, ? examples/s]

snli validation 9842 9842
snli validation 9842 9842


Map:   0%|          | 0/9824 [00:00<?, ? examples/s]

snli test 9824 9824
snli test 9824 9824


Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

snli_inv train 50000 50000
snli_inv train 50000 50000


Map:   0%|          | 0/9842 [00:00<?, ? examples/s]

snli_inv validation 9842 9842
snli_inv validation 9842 9842


Map:   0%|          | 0/9824 [00:00<?, ? examples/s]

snli_inv test 9824 9824
snli_inv test 9824 9824


## Preparing a multi-task data loader and Trainer


In [ ]:
import dataclasses
from torch.utils.data.dataloader import DataLoader
from transformers.training_args import is_torch_tpu_available
#from transformers.trainer import _get_train_sampler

from torch.utils.data.distributed import DistributedSampler
from torch.utils.data.sampler import RandomSampler





class StrIgnoreDevice(str):
    """
    This is a hack. The Trainer is going call .to(device) on every input
    value, but we need to pass in an additional `task_name` string.
    This prevents it from throwing an error
    """
    def to(self, device):
        return self


class DataLoaderWithTaskname:
    """
    Wrapper around a DataLoader to also yield a task name
    """
    def __init__(self, task_name, data_loader):
        self.task_name = task_name
        self.data_loader = data_loader

        self.batch_size = data_loader.batch_size
        self.dataset = data_loader.dataset

    def __len__(self):
        return len(self.data_loader)

    def __iter__(self):
        for batch in self.data_loader:
            batch["task_name"] = StrIgnoreDevice(self.task_name)
            yield batch


class MultitaskDataloader:
    """
    Data loader that combines and samples from multiple single-task
    data loaders.
    """
    def __init__(self, dataloader_dict):
        self.dataloader_dict = dataloader_dict
        self.num_batches_dict = {
            task_name: len(dataloader)
            for task_name, dataloader in self.dataloader_dict.items()
        }
        self.task_name_list = list(self.dataloader_dict)
        self.dataset = [None] * sum(
            len(dataloader.dataset)
            for dataloader in self.dataloader_dict.values()
        )

    def __len__(self):
        return sum(self.num_batches_dict.values())

    def __iter__(self):
        """
        For each batch, sample a task, and yield a batch from the respective
        task Dataloader.

        We use size-proportional sampling, but you could easily modify this
        to sample from some-other distribution.
        """
        task_choice_list = []
        for i, task_name in enumerate(self.task_name_list):
            task_choice_list += [i] * self.num_batches_dict[task_name]
        task_choice_list = np.array(task_choice_list)
        np.random.shuffle(task_choice_list)
        dataloader_iter_dict = {
            task_name: iter(dataloader)
            for task_name, dataloader in self.dataloader_dict.items()
        }
        for task_choice in task_choice_list:
            task_name = self.task_name_list[task_choice]
            yield next(dataloader_iter_dict[task_name])

class MultitaskTrainer(transformers.Trainer):

    def get_single_train_dataloader(self, task_name, train_dataset):
        """
        Create a single-task data loader that also yields task names
        """
        if self.train_dataset is None:
            raise ValueError("Trainer: training requires a train_dataset.")
        train_sampler = (
            RandomSampler(train_dataset)
        )

        data_loader = DataLoaderWithTaskname(
            task_name=task_name,
            data_loader=DataLoader(
              train_dataset,
              batch_size=self.args.train_batch_size,
              sampler=train_sampler,
              #collate_fn=self.data_collator.collate_batch,
            ),
        )
        return data_loader

    def get_train_dataloader(self):
        """
        Returns a MultitaskDataloader, which is not actually a Dataloader
        but an iterable that returns a generator that samples from each
        task Dataloader
        """
        return MultitaskDataloader({
            task_name: self.get_single_train_dataloader(task_name, task_dataset)
            for task_name, task_dataset in self.train_dataset.items()
        })

## Trainning part



In [ ]:
from transformers import DefaultDataCollator
train_dataset = {
    task_name: dataset["train"]
    for task_name, dataset in features_dict.items()
}

trainer = MultitaskTrainer(
    model=multitask_model,
    args=transformers.TrainingArguments(
        output_dir="/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model",
        overwrite_output_dir=True,
        learning_rate=1e-5,
        do_train=True,
        num_train_epochs=1,
        # Adjust batch size if this doesn't fit on the Colab GPU
        per_device_train_batch_size=16,
        save_steps=3000,
    ),
    data_collator=DefaultDataCollator(),
    train_dataset=train_dataset,
)
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


TrainOutput(global_step=6250, training_loss=0.4455130212402344, metrics={'train_runtime': 2238.7202, 'train_samples_per_second': 44.668, 'train_steps_per_second': 2.792, 'total_flos': 6623370086400000.0, 'train_loss': 0.4455130212402344, 'epoch': 1.0})

In [ ]:
torch.save(trainer, "/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/model_g_probas.pth")

In [ ]:
trainer2= torch.load("/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/model_g_probas.pth")



In [ ]:
preds_dict = {}
for task_name,dataset in features_dict.items():
  validation_dataset = {
    task_name: DataLoaderWithTaskname(
        task_name,
        data_loader=DataLoader(dataset["validation"], batch_size=16)
    )
  }
  val_dataloader = MultitaskDataloader(validation_dataset)
  # Hack: something is expecting the dataloader to have a batch size, which is available in the nested dataloader
  val_dataloader.batch_size = 16

  preds_dict[task_name] = trainer2.prediction_loop(
      val_dataloader,
      description="Validation: snli"
  )

Not all data has been set. Are you sure you passed all values?
Not all data has been set. Are you sure you passed all values?


In [ ]:
snli_acc=np.mean(
    np.argmax(preds_dict["snli"].predictions[1],axis=1)
    == snli["validation"]['label']
)

In [ ]:
snli_acc

0.8786831944726682

In [ ]:
snli_inv["validation"]['label'][:10]

tensor([[0.7367, 0.2504, 0.0130],
        [0.1441, 0.8559, 0.0000],
        [0.0000, 0.0964, 0.9036],
        [0.1746, 0.8254, 0.0000],
        [0.0145, 0.4299, 0.5556],
        [0.0000, 0.0643, 0.9357],
        [0.0000, 0.1710, 0.8290],
        [0.1160, 0.8676, 0.0164],
        [0.0491, 0.9509, 0.0000],
        [0.0967, 0.9033, 0.0000]])

In [ ]:
np.argmax(preds_dict["snli"].predictions[1],axis=1)[:20]

array([1, 0, 2, 0, 1, 1, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 1, 2, 0, 2])

In [ ]:
for i in range(20):


  print("**********************************************************")
  print(np.argmax(preds_dict["snli"].predictions[1],axis=1)[i])

  try1=preds_dict["snli_inv"].predictions[1][i]
  exp1=np.exp(try1)
  print(exp1/sum(exp1))


**********************************************************
1
[0.6124225  0.33140457 0.0561729 ]
**********************************************************
0
[2.0660734e-02 9.7842479e-01 9.1449666e-04]
**********************************************************
2
[3.8912726e-04 9.4787655e-03 9.9013209e-01]
**********************************************************
0
[0.04528551 0.9525803  0.00213424]
**********************************************************
1
[0.01209852 0.5246321  0.46326938]
**********************************************************
1
[0.00565621 0.0955972  0.89874655]
**********************************************************
2
[2.7693473e-04 4.0636705e-03 9.9565941e-01]
**********************************************************
1
[0.04228633 0.95391554 0.0037982 ]
**********************************************************
0
[7.0162215e-03 9.9215806e-01 8.2571403e-04]
**********************************************************
0
[0.03008402 0.96893287 0.00098309]
****

In [ ]:
preds_dict = {}
for task_name,dataset in features_dict.items():
  test_dataset = {
    task_name: DataLoaderWithTaskname(
        task_name,
        data_loader=DataLoader(dataset["test"], batch_size=16)
    )
  }
  test_dataloader = MultitaskDataloader(test_dataset)
  # Hack: something is expecting the dataloader to have a batch size, which is available in the nested dataloader
  test_dataloader.batch_size = 16

  preds_dict[task_name] = trainer2.prediction_loop(
      test_dataloader,
      description="Test: snli"
  )

In [ ]:
torch.save(preds_dict,"/content/gdrive/MyDrive/Colab Notebooks/MultiTask_model/test_pred_multimodel_g_probas")